### ISSUE TITLE
Tidal Private API authentication error

### ISSUE THREAD

**Issue by nihal2001** [bbye98/minim#13]
Getting an error on Tidal's web player when trying to authenticate saying "Error
Something went wrong. Please try again. If the error persists, contact customer support."

Tried with and without the browser.

`client_tidal = tidal.PrivateAPI(client_id=os.getenv('TIDAL_CLIENT_ID'), 
                                client_secret=os.getenv('TIDAL_CLIENT_SECRET'),
                                flow="pkce", browser=False)`

**Comment by bbye98** [comment]
Hi there! I was unable to reproduce the issue, both with or without the Playwright browser.

Are you using client credentials from the new TIDAL API? If so, those are not compatible with the private TIDAL API.

**Comment by nihal2001** [comment]
Ya I was using the client credentials from the TIDAL API.
