### ISSUE TITLE
Qobuz: "album-of-the-week" is not supported

### ISSUE THREAD

**Issue by project-owner** [bbye98/minim#2]
There is the following error if you use it:
```
{'status': 'error', 'code': 400, 'message': 'Invalid argument: type (accepted values are 
most-streamed, best-sellers, new-releases, press-awards, editor-picks, most-featured, 
harmonia-mundi, universal-classic, universal-jazz, universal-jeunesse, universal-chanson, 
new-releases-full, recent-releases, ideal-discography, qobuzissims)'}
```

**Comment by bbye98** [comment]
Looks like they removed `album-of-the-week` and `re-release-of-the-week`, and added `harmonia-mundi`, `universal-classic`, `universal-jazz`, `universal-jeunesse`, and `universal-chanson`. I'll update the `get_featured_albums()` methods to reflect this API change.
