### ISSUE TITLE
Getting Tidal API Link

### ISSUE THREAD

**Issue by monke8555** [bbye98/minim#20]
When i login through tidal with the PKCE flow, i dont understand how to do this step:

`After authorizing Minim to access TIDAL on your behalf, copy and paste the URI beginning with 'tidal://login/auth' below.`

Because my browser just shows me this:

Where do I copy it from?
Thank you

**Comment by bbye98** [comment]
Your browser is attempting to redirect you to the TIDAL app since you have it installed. You either have to find a way to disable that redirect, or get the redirect URL by monitoring the Network tab of your browser's Developer Tools (in Chromium-based browsers, you can access this by pressing F12).

**Comment by monke8555** [comment]
Alright I'll try that, and as for the image i specifically took one more to not include my email and accidentally uploaded the first one 😅 Thanks a lot!

**Comment by bbye98** [comment]
@monke8555 As I haven't heard back from you in a while, I'm going to go ahead and close this issue.
