### ISSUE TITLE
Feature request: page through Qobuz favorites

### ISSUE THREAD

**Issue by ronajon** [bbye98/minim#8]
i have a list of > 200 favorite tracks in Qobuz which i want to add to a list.
The current implementation of Qobuz get_favorites does not allow to paginate.

can the method be extended with limit and offset parameters ?
see for instance https://github.com/taschenb/python-qobuz/blob/master/src/qobuz/user.py line 165

**Comment by bbye98** [comment]
Hi there! Thanks for bringing this to my attention. Please see my comments in #9.

**Comment by bbye98** [comment]
Thanks again. I've went ahead and added the `limit` and `offset` parameters to `minim.qobuz.PrivateAPI.get_favorites`, as well as update the documentation to reflect this change.
